version: '3'

env: # global scope
  TF_AUTO: --auto-approve
  KUBE_GET: kubectl get all
  ARGO_DIR: argocd

tasks:
  default:
    desc: "Show this task list"
    cmds:
      - task --list-all

  init:
    internal: true
    cmds:
      - terraform init -upgrade

  plan:
    internal: true
    cmds:
      - terraform plan $TF_AUTO

  apply:
    internal: true
    cmds:
      - terraform apply $TF_AUTO

  destroy:
    desc: "Reset the app, perform Terraform destroy"
    internal: true
    cmds:
      - terraform destroy $TF_AUTO

  argo-credentials:
    desc: "Show the initial ArgoCD admin credential"
    internal: true
    silent: true
    preconditions:
      # Fail when the k8s cluster is not running
      - $KUBE_GET
    cmds:
      - echo "Username is admin"
      - echo $(kubectl -n argocd get secret/argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
      - echo "------------------------------------------------------------"

  argo-ip:
    desc: "Show ArgoCD IP"
    internal: false
    silent: true
    preconditions:
      # Fail when the k8s cluster is not running
      #- kubectl get all
      - $KUBE_GET
    cmds:
      - echo ""
      - echo "------------------------------------------------------------"
      - echo "To view the ArgoCD UI >> https://"$(kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

  argo-cli-login:
    desc: "Login to ArgoCD using Argo CLI"
    internal: false
    silent: true
    preconditions:
      # Fail when the k8s cluster is not running
      #- kubectl get all
      - $KUBE_GET
    cmds:
      - echo ""
      - echo "------------------------------------------------------------"
      - printf "To login via ArgoCD CLI, run:\n argocd login --insecure --username admin --password $(kubectl -n argocd get secret/argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d) $(kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}'):$(kubectl get svc argocd-server -n argocd -o jsonpath='{.spec.ports[1].port}')\n\n"
      - printf "Running 'argocd login'...\n"
      - argocd login --insecure --username admin --password $(kubectl -n argocd get secret/argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d) $(kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}'):$(kubectl get svc argocd-server -n argocd -o jsonpath='{.spec.ports[1].port}')
      - echo "------------------------------------------------------------"

  argo-cli-logout:
    desc: "Logout from Argo CLI"
    internal: false
    silent: true
    preconditions:
      # Fail when the k8s cluster is not running
      #- kubectl get all
      - $KUBE_GET
    cmds:
      - echo ""
      - echo "------------------------------------------------------------"
      - printf "To logout from ArgoCD CLI, run:\n argocd logout $(kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}'):$(kubectl get svc argocd-server -n argocd -o jsonpath='{.spec.ports[1].port}')\n\n"
      - printf "Running 'argocd logout'...\n"
      - argocd logout $(kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}'):$(kubectl get svc argocd-server -n argocd -o jsonpath='{.spec.ports[1].port}')
      - echo "------------------------------------------------------------"

  deploy-app:
    desc: "Deploy ArgoCD Apps"
    cmds:
      - kubectl apply -f control-app.yaml

  destroy-app:
    desc: "Remove the ArgoCD Apps"
    cmds:
      - kubectl delete -f control-app.yaml

  up:
    desc: "Bring up the cluster"
    #dir: $ARGO_DIR
    cmds:
      - task: init
      - task: apply
      - task: argo-ip
      - task: argo-credentials
      - task: argo-cli-login
      #- kubectl apply -f ../control-app.yaml

  cleanup:
    desc: "Destroy and clean up the cluster"
    #dir: $ARGO_DIR
    cmds:
      - task: destroy
      - find . -name '*terraform*' -print | xargs rm -Rf